Rp desktop Portfolio pull request
Godfrey-Alimony/Desktop-Potfolio-version pull request #1
Opened 2022-06-02 09:32 UTC by Godfrey-Alimony

Add markup for the Homepage.
Add stying css file for the Homepage.
Add screenshot for the website.
Add README File for the website.
Add MIT File for the website.
Add icon Files for the website.
Add Image Files for the website.
Add img Files for the website.

2022-06-02 10:01 UTC, danmainah requested changes
Hi @Godfrey-Alimony , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-02 10:01 UTC, danmainah commented on Desktop.html
> +      </header>
- [ ] Kindly check the background images aren't aligned as in the design, check the comparison below to improve your design;

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/171605933-ea221a9c-5744-495a-a05b-94bf398467fa.png) |   ![image](https://user-images.githubusercontent.com/61408860/171605993-9d2e582b-e8e2-4605-9651-2d32af3810f9.png)

2022-06-02 12:24 UTC, Godfrey-Alimony commented on Desktop.css
> +@media (min-width: 992px) {
Done

2022-06-03 08:29 UTC, Godfrey-Alimony commented on Desktop.css
> +
Correction done

2022-06-03 09:07 UTC, Godfrey-Alimony commented on Desktop.html
> +          </form>
The correction did Sir.

2022-06-03 09:39 UTC, Godfrey-Alimony commented on Desktop.html
> +      </header>
Correction done.

2022-06-03 10:10 UTC, Godfrey-Alimony commented on Desktop.html
> +        </section>
Correction done Sir.Thank

2022-06-03 11:20 UTC, Kandy-Peter approved these changes
Hi @TekyRey,

# APPROVED 🟢 

![ObedientGreenAndeancat-max-1mb](https://user-images.githubusercontent.com/80612925/171843592-b0fc5921-ecaa-4f4d-820d-a43ba61ed023.gif)

Great implementation of all the requirements in this milestone. 👏
Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

#### CONGRATULATIONS! 🎉 

##  Optional suggestion

- [ ] **Please, do not open a new repository for each milestone. You have to use the initial one and ensure that you implement each milestone inside.**

# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 11:20 UTC, Kandy-Peter commented on Desktop.html
> +          </form>
- [ ]OPTIONAL:
             -  your should enlarge your inputs width to match the Figma template design.
             - You can also use the CSS property `outline: none;` to remove this black border on input `focus`. It will add a more style to your form 😄
 1. Your design
![image](https://user-images.githubusercontent.com/80612925/171842323-14063114-def4-4f03-8d75-54091549a628.png)
2. The Figma design
![image](https://user-images.githubusercontent.com/80612925/171842403-7126ef39-3f6c-4e80-9cf0-e8ce660fe10b.png)

2022-06-03 11:32 UTC, Godfrey-Alimony commented on Desktop.html
> +          </form>
Thank you so much Sir.Thank

2022-06-03 11:32 UTC, merged